diff --git a/pwn-qemu-kernel/Makefile b/pwn-qemu-kernel/Makefile
index 2644e9a..c601db0 100644
--- a/pwn-qemu-kernel/Makefile
+++ b/pwn-qemu-kernel/Makefile
@@ -13,18 +13,17 @@ kill: ckill skill
 # CTFd Configuration #
 ######################
 
-export FULLNAME  = CTFd challenge name
-export AUTHOR    = LosFuzzys
-export CATEGORY  = pwn
-define DESC
-This is a multiline challenge description!
+$(shell yq ".flag" Manifest.yaml | tr -d '\n' > challenge/flag.txt)
 
-Feel free to add more lines.
-endef
-export DESC
-export FLAG      = $(shell cat challenge/flag.txt)
-export FAKE_FLAG = $(shell cat dist/flag.txt)
-export TAGS      = tag1, tag2, tag with space 
+export FULLNAME := $(shell yq -o yaml ".name" Manifest.yaml)
+export DESC     := $(shell yq -o yaml ".description" Manifest.yaml | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n/<br>/g')
+
+# Config for CTFd
+export AUTHOR   := $(shell yq -o yaml ".author.name" Manifest.yaml)
+export CATEGORY := $(shell yq -o yaml ".category" Manifest.yaml)
+export FLAG     := $(shell cat challenge/flag.txt)
+export FAKE_FLAG := $(shell cat dist/flag.txt)
+export TAGS      := $(shell yq -o=tsv '.tags | join(",")' Manifest.yaml)
 
 ############################
 # Deployment Configuration #
@@ -52,7 +51,7 @@ export NAME=$(shell echo ${UNCLEAN_NAME} | tr "[:upper:]" "[:lower:]")
 # Major: Big features & breakage of interfaces                  (in sync)
 # Minor: Small functionality changes w/ backward compatibility  (in sync)
 # Patch: Small fixes specific to this template                  (not in sync)
-export _VERSION = 1.0.0
+export _VERSION = 1.0.1
 export _TEMPLATE = pwn-qemu-kernel
 
 ########################
@@ -160,9 +159,9 @@ define run_check
 	RETVAL=$$? ; \
 	exec 3>&- ; \
 	echo -e	"\e[1;36m<<<<<<<<<<<<<< END $$(date +'%H:%M:%S')\e[0m"; \
-	printf "$$O" | grep ${FLAG} > /dev/null 2>&1 && \
+	printf "$$O" | grep -F -q -- "${FLAG}" > /dev/null 2>&1 && \
 		echo -e "\033[1;32m[+] Real flag found: ${FLAG}\033[0;0m" || ( \
-	printf "$$O" | grep ${FAKE_FLAG} > /dev/null 2>&1 && \
+	printf "$$O" | grep -F -q -- "${FAKE_FLAG}" > /dev/null 2>&1 && \
 		echo -e "\033[1;32m[+] Fake flag found: ${FAKE_FLAG}\033[0;0m" \
 		|| ([[ "$$RETVAL" -eq "0" ]] && \
 		echo -e "\033[1;31m[!] Flag not found\033[0;0m"; exit 1))
