diff --git a/pwn-jail-debian12.11/challenge/Makefile b/pwn-jail-debian12.11/challenge/Makefile
new file mode 100644
index 0000000..0c5c904
--- /dev/null
+++ b/pwn-jail-debian12.11/challenge/Makefile
@@ -0,0 +1,13 @@
+.PHONY: challenge dist clean
+
+CFLAGS=-O2
+
+challenge: main.c
+	${CC} ${CFLAGS} -o $@ $^
+
+lsp:
+	make -C . clean
+	bear -- make -C . challenge
+
+clean:
+	${RM} challenge compile_commands.json
